export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";
export const UPDATE_FIELD_VALUE = 'CONTACT_UPDATE_FIELD_VALUE';