export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAILURE = "USER_DETAILS_FAILURE";

export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

export const CLEAR_SEARCH = "CLEAR_SEARCH";

export const UPDATE_FIELD_VALUE = 'CONTACT_UPDATE_FIELD_VALUE';

export const UPDATE_SEARCH_ACTIVE_ITEM = 'UPDATE_SEARCH_ACTIVE_ITEM';

export const ADD_ITEM = 'ADD_ITEM';